import pandas as pd
import argparse
import matplotlib.pyplot as plt
import matplotlib
from ggplot import *

matplotlib.style.use('ggplot')

## Graph the factor or percent change specified by each coeficient
## INFILE: path to a coefficient .tsv generated by STATA listcoef
## OUTFILE: path to .pdf of the graph
## COEF_LABELS: path to a coefficient .tsv generated by STATA listcoef
## GROUP BY: path to a .csv file with 2 columns, lang and order by
def graph_coefs(infile,outfile,coef_lables,group_by):
    df = pd.read_table(infile,header=1,index_col=0,na_values='.')
    labels = pd.read_table(coef_lables,header=1,index_col=None,na_values='.')
    labels = labels.rename(columns={'Unnamed: 0':'vars'})
    labels = labels.loc[labels['vars'].str.len() == 2]
    df = df.transpose()
    df = df.reset_index(level=0)
    df = df.rename(columns={'index':'vars'})
    df = df.loc[df['vars'].str[-5:] == 'lang2']
    df = df.merge(labels,on='b')
    df = _group_by(df,'b',group_by)
    ul = df['ul'].subtract(df['b']).values
    ll = df['b'].subtract(df['ll']).values
    errors = [ll,ul]
    df = df.rename(columns={'vars_y':'vars'})
    title = 'Language Coefficients that Predict Edits to Talk Pages'
    ax = df.plot(x='vars',
                 y='b',
                 yerr=errors,
                 kind='bar',
                 legend=False,
                 title=title)
    ax.set_xlabel("Coefficient Value")
    ax.set_ylabel("Language")
    fig = ax.get_figure()
    fig.savefig(outfile)
    plt.show()

## Graph the factor or percent change specified by each coeficient
## INFILE: path to a coefficient .tsv generated by STATA listcoef
## OUTFILE: path to .pdf of the graph
## COEF_TYPE: percent or factor
## GROUP BY: a .csv file with 2 columns, lang and order by
def graph_margins(infile,outfile,coef_type,group_by=None):
    df = pd.read_table(infile,header=1,index_col=0,na_values='.')
    df = df.reset_index(level=0)
    df = df.rename(columns={'index':'vars'})
    if coef_type == 'percent':
        y_column = '%'
        title = 'Percent Increase in Talk Page Edits Predicted By Language'
        ylabel = 'Percent Increase Predicted By Language'
    elif coef_type == 'factor':
        y_column = 'e^b'
        title = 'Factor Increase in Talk Page Edits Predicted By Language'
        ylabel = 'Factor Increase Predicted By Language'
    df = df.loc[df['vars'].str.len() == 2]
    df = _group_by(df,y_column,group_by)
    ax = df.plot(x='vars',
                 y=y_column,
                 kind='bar',
                 legend=False,
                 title=title)
    ax.set_ylabel(ylabel)
    ax.set_xlabel("Language")
    fig = ax.get_figure()
    fig.savefig(outfile)
    plt.show()

def _group_by(df,column=None,infile=None):
    if infile:
        ordered_df = pd.read_csv(infile,index_col=None)
        df = df.merge(ordered_df,on='lang')
        df = df.sort_values('order_by') # fix this
    elif column:
        df = df.sort_values(column)
    else:
        return None
    return df
    
def main():
    parser = argparse.ArgumentParser(description='process wiki data')
    parser.add_argument('-i','--infile')
    parser.add_argument('-o','--outfile')
    parser.add_argument('-c','--coef_type')
    parser.add_argument('-l','--coef_labels')
    parser.add_argument('-b','--group_by')
    args = parser.parse_args()
    if args.coef_type == 'coefs':
        graph_coefs(args.infile,args.outfile,args.coef_labels,args.group_by)
    else:
        graph_margins(args.infile,args.outfile,args.coef_type,args.group_by)
    
if __name__ == "__main__":
    main()
